package com.vu;

import java.util.ArrayList;
import java.util.LinkedList;

// The player object is going to store player names
// Every player will also have a hand
// which is an ArrayList of Card objects
// The player will also know when it's his or her turn
public class Player {

    private String name;
    private ArrayList <Card> hand = new ArrayList<>();
    boolean isMyTurn = false;

    // Constructor with just the name as a string
    Player(String name) {
        this.name = name;

    }

    // Overloading with ArrayList and boolean values
    Player(String name, ArrayList<Card> hand, boolean isMyTurn) {
        this.name = name;
        this.hand = hand;
        this.isMyTurn = isMyTurn;
    }



    // Getters and Setters, auto generated by IntelliJ
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isMyTurn() {
        return isMyTurn;
    }

    public void setMyTurn(boolean myTurn) {
        isMyTurn = myTurn;
    }

    public ArrayList<Card> getHand () {
            return hand;
    }

    public void setHand(ArrayList<Card> hand) {
        this.hand = hand;
    }

    int handSize() {
        return hand.size();
    }

    // This void method is like a secondary toString, to display the player's cards
    public void myHand() {
        for (Card c: hand) {
            System.out.printf("|" + c + "|"); // Make it look like a card
            this.toString();
        }
    }

    // void method to add the Card objects to the ArrayList
    public void addCard(Card card) {
        this.hand.add(card);
    }

    // method removes the Card object from the hand ArrayList
    // useful to simulate the play
    Card moveFrom(Card card) {
        this.hand.remove(card);
        return card;
    }

    // display the player's name
    @Override
    public String toString() {
        return  name;
    }
}



